version: '3'
services:
  jenkins:
    build:
      dockerfile: Dockerfile
      context: ./
      network: host
    ports:
      - '8084:8080'
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    privileged: true
volumes:
  jenkins_home:
    driver: local
